### PR TITLE
Jsuneido

### PR DESCRIPTION
**Pull request by leeeqian**
added Datatbase.Load method to load table when db is running, so we can load table/library table without shutting down server.

### CODE REVIEW

**Comment by apmckinlay** [comment]
Thanks Li. Looks like this should work, but I think it should be done a little bit different. Look at how dump is implemented i.e. as a method in Dbms. The cast to DbmsLocal is a bad smell. It would fail if you were on a client, although it would work if you server eval'ed. Doing it as a method in Dbms requires more changes (DbmsLocal, DbmsRemote, Command) but is more consistent with dump. Then we could add it to cSuneido so it would work when the server was jSuneido.

Also, I don't think we need the default of "" for the table name (in @Params) since it's specifically calling loadTable.

**Comment by leeeqian** [comment]
I see, I mostly wrote (copied) based on DBTools.loadTablePrint, I will take a look at dump.

Thanks for explanation

**Comment by apmckinlay** [comment]
That looks more consistent, thanks!

We have conflicts though. I think because I made a recent change to use try-with-resources which you maybe don't have. Can you merge with the latest?

**Comment by apmckinlay** [comment]
Thanks Li!

**Comment by apmckinlay** [comment]
Found a problem - DbmsUnauth  needs to forward the new load method

I didn't see this error until I "clean'ed" the project in Eclipse. Sometimes the dependency tracking isn't perfect.

**Comment by leeeqian** [comment]
I did notice DbmsUnauth "red" yesterday, but I thought it was always like that on that record.

**Comment by apmckinlay** [comment]
Found one problem in client/server - cSuneido was using int result but jSuneido was using value result. I fixed jSuneido to use int result.

**Pull request merged**
